
#include "main.h"
#include <stdlib.h>
#include <string.h>

#include "ws2812b.h"

// Timer handle
TIM_HandleTypeDef *timer;
uint32_t channel;

// Rows and cols - set by init
uint16_t rows = 0;
uint16_t cols = 0;

// Bunch of zeros used to latch the ws2812
const uint16_t zeros[24] = {0}; // Used to trigger latching

// Look up table for led color bit patterns.  "Waste" 4k of flash but is a
// lot faster (not measured accurately but I'd say about double).
const uint16_t color_value[256][8] = {
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF, LED_ON},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_OFF},
		{LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON, LED_ON}
};

// The actual DMA buffer - contains two halves each container 24 byte
uint16_t dma_buffer[BUFFER_SIZE * 2] = { 0 };

// Pointer to above buffer.  This will be set to the start of the half way point
uint16_t *dma_buffer_pointer;

// Base for calculating RGB values
//float led_angle[LED_ROWS][LED_COLS][3] = { 0 };
//float led_velocity[LED_ROWS][LED_COLS][3] = { 0 };
//uint8_t led_amplitude[LED_ROWS][LED_COLS][3] = { 0 };

// LED RGB values - malloc'ed in init when size is known
uint8_t *led_value;

uint8_t led_state = LED_RES;
uint8_t res_cnt = 0;
uint8_t led_col = 0;
uint8_t led_row = 0;

/*
 * Update next 24 bits in the dma buffer - assume dma_buffer_pointer is pointing
 * to the buffer that is safe to update.
 *
 */
static inline void update_next_buffer() {

	// A simple state machine - we're either resetting (two buffers worth of zeros) or
	// we are transmitting data

	if (led_state == LED_RES) { // Reset state - 10 or more full buffers of zeros

		// This one is simple - we got a bunch of zeros of the right size - just throw
		// that into the buffer
		memcpy(dma_buffer_pointer, zeros, 48);

		res_cnt++;

		if (res_cnt >= LED_RESET_CYCLES) { // done enough reset cycles
			led_col = 0;	// prepare to send data
			led_row = 0;
			led_state = LED_DAT;
		}

	} else { // LED state

		// First let's deal with the current LED
		uint8_t *led = (uint8_t *)(led_value + led_row * led_col);
		for (uint8_t c = 0; c < 3; c++) { // This is the bitch - need to be optimized!

			// Copy values from the pre-filled color_value buffer
			memcpy(dma_buffer_pointer, color_value[led[c]], 16);
			dma_buffer_pointer += 8;

		}

		// Now move to next LED switching to reset state when all leds have been updated
		led_col++; // Next column
		if (led_col >= cols) { // reached top
			led_col = 0; // back to first
			led_row++; // and move on to next row
			if (led_row >= rows) { // reached end

				res_cnt = 0;
				led_state = LED_RES;
			}
		}

	}

}

// Done sending first half of the DMA buffer - this can now safely be updated
void HAL_TIM_PWM_PulseFinishedHalfCpltCallback(TIM_HandleTypeDef *htim) {

	if (htim->Instance == TIM3) {
		dma_buffer_pointer = &dma_buffer[0];
		update_next_buffer();
	}

}

// Done sending the second half of the DMA buffer - this can now be safely updated
void HAL_TIM_PWM_PulseFinishedCallback(TIM_HandleTypeDef *htim) {

	if (htim->Instance == TIM3) {
		dma_buffer_pointer = &dma_buffer[BUFFER_SIZE];
		update_next_buffer();
	}

}

void setLedValue(uint8_t col, uint8_t row, uint8_t led, uint8_t value) {
	led_value[col * row + led] = value;
}

// Just throw values into led_value array - the dma interrupt will
// handle updating the dma buffer when needed
void setLedValues(uint8_t col, uint8_t row, uint8_t r, uint8_t g, uint8_t b) {

	led_value[col * row + R] = r;
	led_value[col * row + G] = g;
	led_value[col * row + B] = b;

}

void ws2812b_init(TIM_HandleTypeDef *init_timer, uint32_t init_channel, uint16_t init_rows, uint16_t init_cols) {

	// Store timer handle for later
	timer = init_timer;

	// Store channel
	channel = init_channel;

	rows = init_rows;
	cols = init_cols;

	led_value = malloc(rows * cols * 3); // Memory for led values

	// Start DMA to feed the PWM with values
	// At this point the buffer should be empty - all zeros
	HAL_TIM_PWM_Start_DMA(timer, channel, (uint32_t*) dma_buffer,
	BUFFER_SIZE * 2);

}
